"""
approval-bridge/models/tradeplan.py
--------------------------------------
Pydantic models for trade plan payloads.

TODO: Extend with full field validation matching the JSON schema
      generated by agent-c's Claude Sonnet output.
"""

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field


class OrderItem(BaseModel):
    """A single order within a trade plan."""

    # TODO: add validator — qty must be positive, limit_price only when order_type == "limit"
    symbol: str = Field(..., description="Ticker symbol, e.g. AAPL", examples=["AAPL"])
    side: str = Field(..., description="buy or sell", examples=["buy"])
    qty: int = Field(..., gt=0, description="Number of shares")
    order_type: str = Field(
        default="market",
        description="market or limit",
        examples=["market"],
    )
    limit_price: Optional[float] = Field(
        default=None,
        description="Limit price (required when order_type == 'limit')",
    )
    time_in_force: str = Field(
        default="day",
        description="day or gtc",
        examples=["day"],
    )


class TradePlanCreate(BaseModel):
    """
    Payload sent by agent-c to POST /plans.

    TODO: Add JSON schema validation for the 'orders' list.
    """

    week: str = Field(..., description="ISO week string, e.g. 2025-W42")
    created_at: datetime = Field(..., description="When the plan was generated")
    orders: list[OrderItem] = Field(default_factory=list)
    rationale: Optional[str] = Field(default=None, description="LLM-generated rationale")


class TradePlan(TradePlanCreate):
    """Full trade plan record including server-assigned ID."""

    id: str = Field(..., description="UUID assigned by approval-bridge on creation")
