"""
agent-c/agent.py
----------------
Core execution logic for agent-c.

Daily workflow (Mon-Fri 9am EST):
  1. Read strategy files from shared volume (wait up to 2h on Mondays)
  2. Call Claude Sonnet to synthesise a trade plan from both strategies
  3. POST trade plan to approval-bridge
  4. Poll for approval (up to APPROVAL_TIMEOUT_MINUTES)
  5. Execute approved plan via myAlpaca; abort if rejected/expired

TODO: Implement full workflow in run_execution().
"""

import json
import logging
import time
from datetime import datetime, timezone

import anthropic

from approval_client import ApprovalStatus, approval_client
from config import config
from executor import execute_plan
from prompts import SYSTEM_PROMPT, TRADE_PLAN_PROMPT_TEMPLATE
from storage import get_current_week_label, read_latest_strategies, write_trade_plan

logger = logging.getLogger(__name__)

MONDAY_STRATEGY_WAIT_SECONDS = 2 * 60 * 60   # 2 hours
MONDAY_STRATEGY_POLL_SECONDS = 5 * 60        # check every 5 min


def _is_monday() -> bool:
    return datetime.now(tz=timezone.utc).weekday() == 0


def _wait_for_monday_strategies() -> dict[str, str]:
    """
    On Mondays, wait up to 2h for agent-a/b to finish writing strategy files.

    TODO: Improve with filesystem event watching (watchdog) instead of polling.
    """
    waited = 0
    while waited < MONDAY_STRATEGY_WAIT_SECONDS:
        strategies = read_latest_strategies()
        if strategies:
            return strategies
        logger.info("Monday: strategies not ready yet, waiting 5 min…")
        time.sleep(MONDAY_STRATEGY_POLL_SECONDS)
        waited += MONDAY_STRATEGY_POLL_SECONDS

    logger.error("Monday: strategy wait timeout — aborting execution")
    return {}


def run_execution() -> None:
    """
    Entry point for agent-c's daily execution task.

    TODO: Replace stub trade plan generation with real Claude Sonnet call.
    """
    logger.info("agent-c: starting daily execution run")

    if _is_monday():
        strategies = _wait_for_monday_strategies()
    else:
        strategies = read_latest_strategies()

    if not strategies:
        logger.error("No strategies available — aborting")
        return

    now = datetime.now(tz=timezone.utc)
    year, week, _ = now.isocalendar()

    strategies_summary = "\n\n".join(
        f"## {key.upper()} Strategy\n{content[:500]}…"
        for key, content in strategies.items()
    )

    prompt = TRADE_PLAN_PROMPT_TEMPLATE.format(
        date=now.strftime("%Y-%m-%d"),
        week=f"{year}-W{week:02d}",
        strategies_summary=strategies_summary,
    )

    # TODO: Replace stub with real Claude Sonnet call
    # client = anthropic.Anthropic(api_key=config.ANTHROPIC_API_KEY)
    # message = client.messages.create(
    #     model="claude-sonnet-4-5",
    #     max_tokens=2048,
    #     system=SYSTEM_PROMPT,
    #     messages=[{"role": "user", "content": prompt}],
    # )
    # raw_json = message.content[0].text
    # plan = json.loads(raw_json)

    plan: dict = {
        "week": f"{year}-W{week:02d}",
        "created_at": now.isoformat(),
        "orders": [],
        "rationale": "TODO: generated by Claude Sonnet",
    }

    write_trade_plan(plan)
    plan_id = plan["id"]

    # TODO: submit to approval-bridge and poll
    # approval_client.submit_plan(plan)
    # status = approval_client.wait_for_approval(plan_id)

    # if status == ApprovalStatus.APPROVED:
    #     execute_plan(plan_id)
    # else:
    #     logger.warning("Plan %s not approved (status=%s) — aborting", plan_id, status)

    logger.info("agent-c: execution run complete (stub — no orders submitted)")
